Improve findAcl phpdoc
symfony/security-acl pull request #83
Opened 2021-07-09 07:38 UTC by VincentLanglet

Hi @nicolas-grekas 

I assume `MutableAclProviderInterface::findAcl` is supposed to return `MutableAclInterface` (and same for findAcls) but currently since `MutableAclProviderInterface` extends `AclProviderInterface`, it inherit of the same phpdoc for those method so return only an `AclInterface`.

This would avoid phpstan-symfony (and psalm-symfony) plugin to introduce some stub about those file.

2021-07-13 14:55 UTC, VincentLanglet commented
Friendly ping @nicolas-grekas @fabpot.

Would you agree to merge such a PR in this repository in order to fix some static analysis (and also narrow the API) issue about the return type of `MutableAclProviderInterface::findAcl` or should we find a solution with psalm-symfony and phpstan-symfony repository ?

Also, should I target main or 3.1 branch ?

Thanks

2021-07-14 15:08 UTC, derrabus requested changes

2021-07-14 15:08 UTC, derrabus commented on Model/MutableAclProviderInterface.php
> +     * @throws AclNotFoundException when there is no ACL
```suggestion
     * {@inheritdoc}
     *
     * @return MutableAclInterface
```

2021-07-14 15:08 UTC, derrabus commented on Model/MutableAclProviderInterface.php
> +     * @throws AclNotFoundException when we cannot find an ACL for all identities
```suggestion
     * {@inheritdoc}
     *
     * @return \SplObjectStorage<ObjectIdentityInterface, MutableAclInterface> mapping the passed object identities to ACLs
```

2021-07-14 15:09 UTC, derrabus commented
The main branch is fine.

2021-07-14 16:34 UTC, VincentLanglet commented on Model/MutableAclProviderInterface.php
> +     * @throws AclNotFoundException when there is no ACL
Done

2021-07-14 16:34 UTC, VincentLanglet commented on Model/MutableAclProviderInterface.php
> +     * @throws AclNotFoundException when we cannot find an ACL for all identities
Done

2021-07-14 16:37 UTC, derrabus approved these changes

2021-07-15 10:25 UTC, wouterj commented
Thanks Vincent!

2021-07-15 10:25 UTC, merged